"""Illustrative impulse responses for the KA11's five DAC filters.

These are textbook stand-ins computed here (windowed-sinc low-pass filters at 8x oversampling,
converted to minimum phase where relevant), not measurements of the KA11. They show the
characteristic shape of each filter type: where the ringing sits and how long it lasts.
"""
try:
    import numpy as np
except ImportError:  # the packaged app ships precomputed curves instead (see load_curves)
    np = None

OVERSAMPLE = 8
WINDOW = (-6, 14)  # displayed span, in original sample periods around the main peak

# (short description, curve) in ka11.FILTERS order
DESCRIPTIONS = (
    "Sharp cutoff · ringing only after the peak",
    "Sharp cutoff · symmetric ringing before and after",
    "Gentle cutoff · brief ringing only after the peak",
    "Gentle cutoff · short symmetric ringing",
    "No filtering · no ringing, slightly softer treble",
)


def _lowpass(taps, beta):
    """Windowed-sinc low-pass with its cutoff at the original Nyquist frequency."""
    n = np.arange(taps) - (taps - 1) / 2
    return np.sinc(n / OVERSAMPLE) * np.kaiser(taps, beta)


def _minimum_phase(h, n_fft=1 << 14):
    """Same magnitude response, energy moved to the start (homomorphic / real-cepstrum method)."""
    log_mag = np.log(np.maximum(np.abs(np.fft.fft(h, n_fft)), 1e-12))
    cep = np.fft.ifft(log_mag).real
    fold = np.zeros(n_fft)
    fold[0] = fold[n_fft // 2] = 1
    fold[1:n_fft // 2] = 2
    return np.fft.ifft(np.exp(np.fft.fft(cep * fold))).real[:len(h)]


def _window(h):
    """Crop to WINDOW around the main peak and normalise to a peak of 1."""
    peak = int(np.argmax(np.abs(h)))
    start, stop = peak + WINDOW[0] * OVERSAMPLE, peak + WINDOW[1] * OVERSAMPLE
    padded = np.concatenate([np.zeros(max(0, -start)), h, np.zeros(max(0, stop - len(h)))])
    offset = max(0, -start)
    out = padded[start + offset:stop + offset]
    return out / np.max(np.abs(out))


def impulse_responses():
    fast = _lowpass(OVERSAMPLE * 40 + 1, 10)  # long filter: steep cutoff, long ringing
    slow = _lowpass(OVERSAMPLE * 6 + 1, 4)  # short filter: gentle cutoff, short ringing
    nos = np.ones(OVERSAMPLE)  # zero-order hold: each sample just held flat
    return [_window(h) for h in (_minimum_phase(fast), fast, _minimum_phase(slow), slow, nos)]


def load_curves(points=161):
    """Curves for drawing: precomputed ones if present (the packaged app has no numpy), else computed."""
    try:
        from filter_curves_data import CURVES
        return CURVES
    except ImportError:
        return [_downsample(c, points) for c in impulse_responses()]


def _downsample(curve, points):
    idx = np.linspace(0, len(curve) - 1, points).round().astype(int)
    return [round(float(v), 4) for v in curve[idx]]


if __name__ == "__main__":  # regenerate the precomputed curves bundled into the exe
    curves = [_downsample(c, 161) for c in impulse_responses()]
    with open("filter_curves_data.py", "w", encoding="utf-8") as f:
        f.write('"""Generated by filter_shapes.py - illustrative impulse responses, 161 points each."""\n')
        f.write(f"CURVES = {curves!r}\n")
    print("wrote filter_curves_data.py")
